version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
  celery:
    build: .
    command: celery -A celery_worker worker --loglevel=info --concurrency=1
    depends_on:
      - redis
    volumes:
      - .:/app
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount custom Nginx configuration
    depends_on:
      - web  # Ensure Nginx starts after the web service
