version: '3.8'
services:
  web:
    build: .
    ports:
      - "8002:8000"
    depends_on:
      - redis
    volumes:
      - .:/app

  celery:
    build: .
    command: celery -A celery_worker worker --loglevel=info --concurrency=1
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
