version: '3.8'

services:
  web:
    build: .
    expose:
      - "8002"
    depends_on:
      - redis
    volumes:
      - .:/app

  celery:
    build: .
    command: celery -A celery_worker worker --loglevel=info --concurrency=1
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./static:/app/static

  redis:
    image: redis:alpine
    expose:
      - "6379"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
    depends_on:
      - web